/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Connector.Methods2;
import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Tanmoy Mitra & Himanshi Dewangan
 */
public final class Add_New extends javax.swing.JFrame {

    Connection con;

    /**
     * Creates new form View_Quiz
     */
    public Add_New(String c) {
        initComponents();
        filldatai1();
        jComboBox1.setSelectedItem(c);

    }
    String ans_one, ans_two, ans_three, ans_four, cor_ans;

    public void filldatai1() {
        try {
            String databasename = "bug2db";
            String url = "jdbc:mysql://localhost:3306/";
            String user = "root";
            String pass = "root";
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(url + databasename, user, pass);

            Statement st = con.createStatement();
            ResultSet r = st.executeQuery("select * from courses");

            while (r.next()) {

                jComboBox1.addItem(r.getString("course_name"));
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Failed to Connect to Database", "Error Connection", JOptionPane.WARNING_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ques_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ques = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        answer_one = new javax.swing.JTextField();
        answer_two = new javax.swing.JTextField();
        answer_three = new javax.swing.JTextField();
        answer_four = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Course -");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 270, 30));

        jLabel3.setText("Question No. -");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 200, -1, 30));

        ques_id.setText(" ");
        getContentPane().add(ques_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 200, 138, 30));

        ques.setColumns(20);
        ques.setRows(5);
        jScrollPane1.setViewportView(ques);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 950, 140));

        jLabel4.setText("Answer One ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, 30));

        jLabel5.setText("Answer Two ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, -1, 30));

        jLabel6.setText("Answer Three ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, -1, 30));

        jLabel7.setText("Answer Four ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, -1, 30));

        answer_one.setText(" ");
        getContentPane().add(answer_one, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 330, 30));

        answer_two.setText(" ");
        getContentPane().add(answer_two, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 330, 30));

        answer_three.setText(" ");
        answer_three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_threeActionPerformed(evt);
            }
        });
        getContentPane().add(answer_three, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 510, 330, 30));

        answer_four.setText(" ");
        answer_four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answer_fourActionPerformed(evt);
            }
        });
        answer_four.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                answer_fourKeyTyped(evt);
            }
        });
        getContentPane().add(answer_four, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 550, 330, 30));

        jLabel8.setText("Correct Answer -");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 430, 100, 30));

        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 290, 30));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 640, 80, 30));

        jButton2.setBackground(new java.awt.Color(87, 184, 70));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 90, 80, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Edit Questions");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 40));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Copyright © 2022 by Tanmoy Mitra & Himanshi Dewangan");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 720, -1, 20));

        jPanel1.setBackground(new java.awt.Color(25, 72, 128));
        jPanel1.setPreferredSize(new java.awt.Dimension(1025, 42));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Amity Exam Portal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(1124, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 60));

        jPanel5.setBackground(new java.awt.Color(241, 184, 32));
        jPanel5.setMaximumSize(new java.awt.Dimension(1366, 4));
        jPanel5.setMinimumSize(new java.awt.Dimension(1366, 4));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1366, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void answer_threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_threeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_threeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Methods2 mm = new Methods2();
        String course = "" + jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        String questions = ques.getText().trim();
        ans_one = answer_one.getText().trim();
        ans_two = answer_two.getText().trim();
        ans_three = answer_three.getText().trim();
        ans_four = answer_four.getText().trim();
        cor_ans = "" + jComboBox2.getSelectedItem();
        String q_id = ques_id.getText().trim();
        try {
            int ros = mm.AddQues(course, questions, ans_one, ans_two, ans_three, ans_four, cor_ans, q_id);
            if (ros > 0) {
                JOptionPane.showMessageDialog(null, "Question Added Successfully !!");
                String s = "" + jComboBox1.getSelectedItem();
                new Add_New(s).setVisible(true);
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Check Connection");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void answer_fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answer_fourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answer_fourActionPerformed

    private void answer_fourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_answer_fourKeyTyped

        // TODO add your handling code here:
    }//GEN-LAST:event_answer_fourKeyTyped

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if ((jComboBox2.getSelectedItem()) == null) {
            jComboBox2.addItem(ans_one);
            jComboBox2.addItem(ans_two);
            jComboBox2.addItem(ans_three);
            jComboBox2.addItem(ans_four);
        }                      // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Questions().setVisible(true);
        dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Add_New("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField answer_four;
    public javax.swing.JTextField answer_one;
    public javax.swing.JTextField answer_three;
    public javax.swing.JTextField answer_two;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ques;
    private javax.swing.JTextField ques_id;
    // End of variables declaration//GEN-END:variables
}
